# Generated by Django 2.2 on 2019-10-30 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191030_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergithub',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usergithub', to=settings.AUTH_USER_MODEL),
        ),
    ]
