# Generated by Django 2.2 on 2019-11-04 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20191014_1133'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20191104_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(verbose_name='Время создания')),
                ('end_at', models.DateField(verbose_name='Время создания')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Project', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command', to=settings.AUTH_USER_MODEL, verbose_name='Программист')),
            ],
        ),
    ]
