# Generated by Django 2.2 on 2019-11-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='created_at',
            field=models.DateField(verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='command',
            name='end_at',
            field=models.DateField(verbose_name='Дата окончания работы'),
        ),
    ]
