# Generated by Django 2.2 on 2019-11-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191104_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Command',
        ),
    ]
