# Generated by Django 2.2 on 2019-09-25 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statuses', models.CharField(blank=True, max_length=20, null=True, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='TypeChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, max_length=400, null=True, verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('status', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='webapp.StatusChoice')),
                ('type', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, related_name='type', to='webapp.TypeChoice')),
            ],
        ),
    ]
