# Generated by Django 2.2 on 2019-10-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschoice',
            name='statuses',
            field=models.CharField(default='', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='summary',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='typechoice',
            name='types',
            field=models.CharField(default='', max_length=20, verbose_name='Тип'),
        ),
    ]
