# Generated by Django 2.2 on 2019-10-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191009_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschoice',
            name='statuses',
            field=models.CharField(max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='typechoice',
            name='types',
            field=models.CharField(max_length=20, verbose_name='Тип'),
        ),
    ]
