# Generated by Django 2.2 on 2019-10-09 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20191009_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BigIntegerField(verbose_name='Счетчик')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=400, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Время обновления')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('closed', 'Закрыт')], default='active', max_length=20, verbose_name='Status')),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='project',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project', to='webapp.Project', verbose_name='Проект'),
        ),
    ]
