# Generated by Django 2.2 on 2019-10-09 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20191009_1840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
