# Generated by Django 2.2 on 2019-11-06 07:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0011_command'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Command',
            new_name='Team',
        ),
    ]
