# Generated by Django 2.2 on 2019-11-12 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20191106_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='team',
            name='end_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания работы'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
