# Generated by Django 2.2 on 2019-11-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20191112_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='team',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания работы'),
        ),
    ]
