# Generated by Django 2.2 on 2019-11-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20191113_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='webapp.Project', verbose_name='Проект'),
        ),
    ]
